// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'DefaultFirebaseOptions.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAfmi_-AZi4T0qltnlM8p_gwUUo2vcnhw',
    appId: '1:353988480054:web:d4bf5ab6d884bed52a5c97',
    messagingSenderId: '353988480054',
    projectId: 'nearestworkspace',
    authDomain: 'nearestworkspace.firebaseapp.com',
    storageBucket: 'nearestworkspace.firebasestorage.app',
    measurementId: 'G-EPRRJ31VWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogj0yd5S4ZsK1-ijaN9JRH1iaWph6qT8',
    appId: '1:353988480054:android:ee749b732dd97e122a5c97',
    messagingSenderId: '353988480054',
    projectId: 'nearestworkspace',
    storageBucket: 'nearestworkspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZu9XTLBHe96CfvoxjUr4figAWQb1Vbxs',
    appId: '1:353988480054:ios:347b1c4e9d2a37652a5c97',
    messagingSenderId: '353988480054',
    projectId: 'nearestworkspace',
    storageBucket: 'nearestworkspace.firebasestorage.app',
    androidClientId: '353988480054-ccb1jf498r3avq374t7vmvruji2v4gvd.apps.googleusercontent.com',
    iosClientId: '353988480054-l1f80rtjj04k5mimfinf5s5d2hoo16vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZu9XTLBHe96CfvoxjUr4figAWQb1Vbxs',
    appId: '1:353988480054:ios:347b1c4e9d2a37652a5c97',
    messagingSenderId: '353988480054',
    projectId: 'nearestworkspace',
    storageBucket: 'nearestworkspace.firebasestorage.app',
    androidClientId: '353988480054-ccb1jf498r3avq374t7vmvruji2v4gvd.apps.googleusercontent.com',
    iosClientId: '353988480054-l1f80rtjj04k5mimfinf5s5d2hoo16vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAfmi_-AZi4T0qltnlM8p_gwUUo2vcnhw',
    appId: '1:353988480054:web:eb4df6c91463fc272a5c97',
    messagingSenderId: '353988480054',
    projectId: 'nearestworkspace',
    authDomain: 'nearestworkspace.firebaseapp.com',
    storageBucket: 'nearestworkspace.firebasestorage.app',
    measurementId: 'G-6H0QKYMGXJ',
  );
}
