// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // تم التعديل هنا: إذا كان النظام ويب أو ويندوز سيعود بإعدادات الويب مباشرة
    if (kIsWeb || defaultTargetPlatform == TargetPlatform.windows) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web; // أمان إضافي في حال تخطي الشرط العلوي
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGe4b8b3jPU59_VC9vGgeeTbwevwQUhk',
    appId: '1:644719264139:web:fd502ca45a8fbfab70ef8e',
    messagingSenderId: '644719264139',
    projectId: 'studyspot-gaza',
    authDomain: 'studyspot-gaza.firebaseapp.com',
    storageBucket: 'studyspot-gaza.firebasestorage.app',
    measurementId: 'G-68Q9HWCST1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjmELB0z48hIh9ndM63a9VzSJ51ANoB8',
    appId: '1:644719264139:android:27006b8496a0443870ef8e',
    messagingSenderId: '644719264139',
    projectId: 'studyspot-gaza',
    storageBucket: 'studyspot-gaza.firebasestorage.app',
  );
}